### ISSUE TITLE
Implementation of permission across separate tag

### ISSUE THREAD

**Issue by Quany22000** [Nearata/flarum-ext-dsts#1]
would it be a bother if you were able to make this extension able to say like have bypass permissions in different tags as when I access it, it's only one permission right now Can bypass like and its for global it doesn't expand over any other tags, because I have a rule section and don't necessarily want them to like to see that content so If you could help
![Screenshot_1](https://user-images.githubusercontent.com/86467256/123479462-d4262a80-d5b5-11eb-86ca-063d31dfb850.png)

**Comment by Nearata** [comment]
Should be fixed in `2.1.0`
