### ISSUE TITLE
adding custom bbcode doesn't work

### ISSUE THREAD

**Issue by BeyondIM** [Nearata/flarum-ext-dsts#2]
Thank you for this great extension. At present, the working mode of dsts is that when users don't reply, they cannot see all the content of first post. I tried to adjust to add a bbcode, when the users don't reply, only the content surrounded by bbode could not be seen.

![snipaste20210906_161530](https://cdn.jsdelivr.net/gh/BeyondIM/forum_assets@master/snipaste20210906_161530.1dxkp3fpvyrk.jpg)

![snipaste20210906_161608](https://cdn.jsdelivr.net/gh/BeyondIM/forum_assets@master/snipaste20210906_161608.6oj4y7y5w1s0.jpg)

But this doesn't work.  I am a novice, Can you help me? tks.

**Comment by Nearata** [comment]
i tried your code and it works as expected. what doesn't work to you? can you show me the result you see?

![Screenshot_2](https://user-images.githubusercontent.com/26413668/132203116-2dcf47d0-1c78-4663-a0a5-9af7c4f97786.png)
![Screenshot_1](https://user-images.githubusercontent.com/26413668/132203139-3624da48-3a4a-4331-b4b6-962970443554.png)

**Comment by Nearata** [comment]
try to change `{TEXT}` to `{ANYTHING}`

**Comment by BeyondIM** [comment]
It works now. tks.

**Comment by BeyondIM** [comment]
I'm so sorry it doesn't work again. Once I add code below, It has the following error.

```php
  (new Extend\Formatter)
    ->configure(function (Configurator $config) {
      $config->BBcodes->addCustom(
        '[REPLY]{ANYTHING}[/REPLY]',
        '<reply>{ANYTHING}</reply>'
      );
    }),
```

![2021-09-08_21-26](https://cdn.jsdelivr.net/gh/BeyondIM/forum_assets@master/2021-09-08_21-26.633knczv3j00.png)

and I try to perform the following operations, error still exist.

```bash
php flarum cache:clear
rm -rf storge/cache/*
rm -rf storge/formatter/*
```

I know this problem has nothing to do with your dsts extension, but I installed your another great extension embed-video　which has similar code, It works perfect. I don't know what the problem is.

Could you give me some directions? Thank you very much.

**Comment by Nearata** [comment]
you need this

`use s9e\TextFormatter\Configurator;`

add this after the others

**Comment by BeyondIM** [comment]
I've added `use s9e\TextFormatter\Configurator;` like the top screenshot.

**Comment by Nearata** [comment]
remove the import

and change the line

```php
->configure(function (Configurator $config) {
```

to

```php
->configure(function ($config) {
```

clear cache and see if it works

**Comment by BeyondIM** [comment]
It doesn't work yet.

![2021-09-08_22-09](https://cdn.jsdelivr.net/gh/BeyondIM/forum_assets@master/2021-09-08_22-09.45br8uubfqg0.png)

I found [this link](https://discuss.flarum.org/d/21874-deactivating-bbbbcode-an-error-occurred-while-trying-to-load-the-page-failure) which encountered the same problem as me. The user solves the problem by trying to deactivate other extensions that have potential conflicts. I will try this way also. tks.
