### ISSUE TITLE
additional features

### ISSUE THREAD

**Issue by Ruszona** [Nearata/flarum-ext-dsts#3]
I propose to add the ability to 1) choose for which groups to hide the first post 2) hide only files 3) hide with bbcode

**Comment by Nearata** [comment]
Thank you for your suggestions !

Can you elaborate the n. 2?

**Comment by Ruszona** [comment]
> Thank you for your suggestions !
> 
> Can you elaborate the n. 2?

https://discuss.flarum.org/d/4154-friendsofflarum-upload-the-intelligent-file-attachment-extension

**Comment by Nearata** [comment]
done in `2.3.0`
